export const ADD_NEW_PROVIDER = "ADD_NEW_PROVIDER";
export const ADD_PROVIDERS_FIELD = "ADD_PROVIDERS_FIELD";
export const REMOVE_PROVIDERS_FIELD = "REMOVE_PROVIDERS_FIELD";
export const LOAD_SUPPLIERS = 'LOAD_SUPPLIERS';
export const LOAD_SUPPLIER = 'LOAD_SUPPLIER';