export const LOAD_SUPPLIERS = 'LOAD_SUPPLIERS';
export const LOAD_SUPPLIER = 'LOAD_SUPPLIER';
export const IS_LOADING_SUPPLIER = 'IS_LOADING_SUPPLIER';
export const LOAD_QUALITY_SURVEY_REPLY = 'LOAD_QUALITY_SURVEY_REPLY'
