export const LOAD_SUPPLIERS = 'LOAD_SUPPLIERS';
export const LOAD_SUPPLIER = 'LOAD_SUPPLIER';
export const IS_LOADING_SUPPLIER = 'IS_LOADING_SUPPLIER';
export const LOAD_QUALITY_SURVEY_REPLY = 'LOAD_QUALITY_SURVEY_REPLY';
export const REMOVE_SUPPLIER = 'REMOVE_SUPPLIER';
export const SUPPLIER_VIEW_ACTIVE_TAB = 'SUPPLIER_VIEW_ACTIVE_TAB';
export const PRELOAD_SUPPLIER_CONTACT = 'PRELOAD_SUPPLIER_CONTACT';
