export const LOAD_TEAMS = 'LOAD_TEAMS';
export const LOAD_TEAM = 'LOAD_TEAM';
export const LOAD_USERS = 'LOAD_USERS';
export const ADD_MEMBER_CREATION = 'ADD_MEMBER_CREATION';
export const REMOVE_MEMBER_CREATION = 'REMOVE_MEMBER_CREATION';
export const ADD_MEMBER_EDITION = 'ADD_MEMBER_EDITION';
export const REMOVE_MEMBER_EDITION = 'REMOVE_MEMBER_EDITION';
export const LOAD_USER = 'LOAD_USER';